### ISSUE TITLE
Get data from HTTP endpoints

### ISSUE THREAD

**Issue by ahinko** [ahinko/tcpsolis2mqtt#18]
- [ ] Rename `modbus.yaml` to `sensors.yaml`
- [ ] Only poll when data logger has been offline and comes back online
- [ ] Only poll if config exists
- [ ] Sensors must also be`active` in `sensors.yaml`
- [ ] Add `protocol` setting to `sensors.yaml`. `http`/`modbus`
```yaml
- name: inverter_firmware
  description: Inverter Firmware
  protocol: http
  active: true
```
- [ ] Add config options:
```yaml
datalogger:
  http:
    enabled: True
    username: admin
    password: 123456789
```

We can fix all these sensors this way:
- #8
- #9 
- #10 
- #11 
- #12 
- #13
